// old-old/src/routes/[resourceid]/edit/glossary-term.svelte
<script lang="ts">
	import MediaSelector from '$lib/components/media-selector.svelte';
	import type { Glossary } from '$lib/schemas';
	import { TextareaAutosize } from 'runed';
	import { Modal } from 'uisv';

	type Props = {
		term: Glossary['terms'][number];
	};

	let { term = $bindable() }: Props = $props();
	let definition_textarea = $state<HTMLTextAreaElement>();
	let text_textarea = $state<HTMLTextAreaElement>();

	new TextareaAutosize({ element: () => definition_textarea, input: () => term.definition.text });
	new TextareaAutosize({ element: () => text_textarea, input: () => term.text });
</script>

<tr>
	<td class="">
		<div class="relative">
			<textarea
				bind:this={text_textarea}
				bind:value={term.text}
				placeholder="Enter term"
				class={[
					'w-full outline-none h-16 bg-surface-muted rounded p-4 resize-none',
					term.media ? '' : '',
				]}></textarea>

			<Modal></Modal>
		</div>
	</td>

	<td class="">
		<textarea
			bind:this={definition_textarea}
			bind:value={term.definition.text}
			placeholder="Enter definition"
			class="w-full outline-none h-16 bg-surface-muted rounded p-4 resize-none"></textarea>
	</td>
</tr>

<MediaSelector open={true} />

// app/components/resource/glossary-term.vue
<script setup lang="ts">
import { useTextareaAutosize } from '@vueuse/core'
import type { Glossary } from '~/composables/schemas'

const term = defineModel<Glossary['terms'][0]>({ required: true })
const definition_textarea = useTemplateRef('text_textarea')
const text_textarea = useTemplateRef('text_textarea')

useTextareaAutosize({
  element: definition_textarea,
  input: term.value.definition.text
})
useTextareaAutosize({ element: text_textarea, input: term.value.text })
</script>

<template>
  <tr>
    <td class="">
      <div class="relative">
        <textarea
          ref="text_textarea"
          v-model="term.text"
          placeholder="Enter term"
          :class="[
            'w-full outline-none h-16 bg-surface-muted rounded p-4 resize-none',
            term.media ? '' : ''
          ]"
        ></textarea>

        <Modal></Modal>
      </div>
    </td>

    <td class="">
      <textarea
        ref="definition_textarea"
        v-model="term.definition.text"
        placeholder="Enter definition"
        class="w-full outline-none h-16 bg-surface-muted rounded p-4 resize-none"
      />
    </td>
  </tr>

  <MediaSelector :open="true" />
</template>
